# Generated by Django 3.1.5 on 2021-01-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210113_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '테스트 페이지 사용자', 'verbose_name_plural': '테스트 페이지 이용자'},
        ),
    ]
